name = "rahmatnugraha"
compatibility_date = "2026-02-20"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "resume-leads"
database_id = "a9d1fc15-93ce-4ff4-8b70-e6e9b8a5561d"
